### ISSUE TITLE
MCP4822 DAC missed pin

### ISSUE THREAD

**Issue by rgrokett** [tteskac/rpi-lasershow#1]
Just FYI, I had to connect pin raspberry Pi pin 22 (GPIO 25) to the LDAC pin 5 on the MCP4822 DAC in order to get the patterns to work properly.  Used this schematic from the ABelectronics ADCDAC Pi library to find the pins:
https://www.abelectronics.co.uk/docs/pdf/schematic-adc-dac-pi.pdf

With this, the test ild pattern looks pretty good even w/o using OpAmps to get + - 5v 
 
Otherwise, the software you have written appears to be working just fine!  Thanks!

**Comment by tteskac** [comment]
Hi @rgrokett, thanks for pointing that out. I will update the readme :)

**Comment by tteskac** [comment]
I updated Readme now with the correct pinout.
Just for the record: Pi pin 22 is actually not used by the software, and by default, when not initialized, the value of it is LOW (0V/GND). This means that LDAC pin (latch) can be connected to any GND pin actually and by that it will automatically 'latch' the value to output pins (VoutA/VoutB) as soon as Pi sends the value. This is why it works for you with pin 22, it's basically GND. :)
I will close this issue now.
